FROM python:3.7-alpine3.9
LABEL maintainer="Nictiz <info@snomed.nl>"

RUN pip install requests_toolbelt

# Create a working directory
RUN mkdir /app
WORKDIR /app

COPY ./ingest.py ./ingest.py

ENTRYPOINT ["python", "ingest.py"]